name: My CI workflow

on:
  push:

jobs:
  hello:
    name: My Hello Job
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World 
        run: echo "Hello World"
      - name: Second steps
        run: echo "second"

  goodbye:
    name: My Goodbye job
    needs: hello
    runs-on: windows-latest
    steps:
      - run: echo "Goodbye"

  test: 
    name: Test the Python package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with: 
          python-version: "3.10"
      - name: Install the package
        run: pip install .[test]
      - name: Run the tests
        run: pytest -vv