name: My CI workflow

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch: 

jobs:
  hello:
    name: My Hello Job
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World 
        run: echo "Hello World"
      - name: Second steps
        run: echo "second"

  goodbye:
    name: My Goodbye job
    needs: hello
    runs-on: windows-latest
    steps:
      - run: echo "Goodbye"

  linting:
    name: Check format
    runs-on: ubuntu-latest
    steps:
      - name: install ruff
        uses: astral-sh/ruff-actions
      - name: run check
        run: ruff check 

  test: 
    name: Test the Python package
    needs: linting
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        python-version: ["3.10", "3.14"]
        platform: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - python-version: "3.13"
            platform: "macos-15"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with: 
          python-version: ${{ matrix.python-version }}
      - name: Install the package
        run: pip install .[test]
      - name: Run the tests
        run: pytest -vv